name: dartz_serializable
description: A small package that adds json_serializable support to dartz-monads
version: 0.2.0-nullable.1
homepage: https://github.com/FaFre/dartz_serializable
environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.0.0
  pedantic: ^1.9.0
  test: ^1.14.4
dependencies:
  dartz: ^0.10.0-nullsafety.1
  json_annotation: ^4.0.0
